DROP TABLE IF EXISTS member CASCADE;

CREATE TABLE member(
   id bigint generated by default as identity,
   name varchar2(255),
   primary key (id)
);

INSERT INTO member(name) VALUES('DevAndy');
INSERT INTO member(name) VALUES('Kami');
INSERT INTO member(name) VALUES('Programmer');

SELECT * FROM member;